# Environment Functions
- Get the matrix from the frontier


0 represents a blank tile.

In [7]:
import numpy as np
from copy import deepcopy

In [8]:
class Node:
    """
    This class contains the attributes carried by one node
    """
    def __init__(self, matrix):
        self.matrix = matrix
        self.is_visited = False

In [9]:
def get_position(matrix, value):
    """
    Gets the positon of the blank tile and returns the row 
    and column coordinates.
    """
    
    if value < 0 or value > 8:
        raise Exception("Given value is not in the matrix!")
    else:
        for row in range(len(matrix)):
            for col in range(len(matrix)):
                if matrix[row][col] == value:
                    return row, col

In [10]:
def get_matrix(matrix, row, col, move):
    """
    Returns the possible transitions of the blank tile.
    """
    
    blank_tile = matrix[row][col]
    swap_tile = matrix[move[0]][move[1]]
    matrix[row][col] = swap_tile
    matrix[move[0]][move[1]] = blank_tile
    return matrix

In [13]:
def get_frontier(node: Node):
    """
    Returns the list of all possible transition matrix for the current postion of the blank tile
    """
    
    print("Current State: \n", node.matrix, "\n")
    # Check if the node is visited or not, mark visited if not
    if node.is_visited == False:
        node.is_visited = True

    row, col = get_position(node.matrix, 0)
    possible_moves = list()
    if row > 0:
        possible_moves.append((row - 1, col))
    if row < 2:
        possible_moves.append((row + 1, col))
    if col > 0:
        possible_moves.append((row, col - 1))
    if col < 2:
        possible_moves.append((row, col + 1))
        
    frontier = list()
    for move in possible_moves:
        copy_matrix = deepcopy(node.matrix)
        frontier.append(get_matrix(copy_matrix, row, col, move))

    return frontier

In [15]:
CURR_STATE = np.array([[1, 3, 2], [8, 0, 4], [7, 6, 5]])
frontier = get_frontier(Node(CURR_STATE))

print("Possible Transition states: ")
for matrix in frontier:
    print("\n", matrix)

Current State: 
 [[1 3 2]
 [8 0 4]
 [7 6 5]] 


Possible Transition states: 

 [[1 0 2]
 [8 3 4]
 [7 6 5]]

 [[1 3 2]
 [8 6 4]
 [7 0 5]]

 [[1 3 2]
 [0 8 4]
 [7 6 5]]

 [[1 3 2]
 [8 4 0]
 [7 6 5]]
